version: "3.9"  # optional since v1.27.0
services:
  db:
    container_name: go-mysql
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=recordings
      - MYSQL_USER=go_user
      - MYSQL_PASSWORD=go_pwd